# -*- coding: utf-8 -*-
"""Sign_language_to_speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQ2M3kV2J1GwRRuv62IpYPRrsQQitFFn
"""

!pip install datasets

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, TrainingArguments, Trainer
from datasets import load_dataset, Dataset
import json

# Load and process dataset
with open("/content/train_fixed.json", "r") as file:
    data = json.load(file)

# Convert to Hugging Face Dataset
dataset = Dataset.from_dict({
    "input": [entry["input"] for entry in data],
    "output": [entry["output"]["text"] for entry in data],
})

# Split dataset into train and test sets
train_test_split = dataset.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

# Model and tokenizer
model_name = "facebook/bart-base"  # Use a smaller BART model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Tokenization
def preprocess_function(examples):
    inputs = examples["input"]
    outputs = examples["output"]

    model_inputs = tokenizer(inputs, max_length=64, truncation=True, padding="max_length")
    labels = tokenizer(outputs, max_length=64, truncation=True, padding="max_length")

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# Apply tokenization
tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Training setup
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-3,
    per_device_train_batch_size=8,  # Reduced batch size
    per_device_eval_batch_size=8,   # Reduced batch size
    num_train_epochs=10,  # Reduced number of epochs
    weight_decay=0.01,
    save_total_limit=1,
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=10,
    fp16=True,  # Enable mixed precision
    gradient_accumulation_steps=2,  # Gradient accumulation for effective batch size
    push_to_hub=False,
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
)

# Train the model
trainer.train()

# Save the model
trainer.save_model("finetuned_bart_base")

!pip install transformers
!pip install datasets
!pip install sentencepiece

!git clone https://github.com/smtiitm/Fastspeech2_HS.git

!pip install torch torchaudio

!pip install cudatoolkit

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Fastspeech2_HS

!pip install -r requirements.txt  # If there's a requirements.txt file

# Step 5: Install other dependencies or libraries that might be in environment.yml
!pip install numpy scipy matplotlib librosa

!cd ..
!git clone https://github.com/jik876/hifi-gan.git

!pip install flash-attn

# Commented out IPython magic to ensure Python compatibility.
!cd ..
# %cd /content/
!ls

!pip install espnet

!pip install --upgrade "jax[cuda12]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

!ls
!pip install numpy==1.26.4

!pip install num2words

!mkdir phone_dict

!python3 /content/Fastspeech2_HS/inference.py --sample_text "श्रीलंका और पाकिस्तान में खेला जा रहा एशिया कप अब तक का सबसे विवादित टूर्नामेंट होता जा रहा है।" --language hindi --gender male --alpha 1

!pip install flask pyngrok

import os
import json
from flask import Flask, request, jsonify, send_file
from pyngrok import ngrok
import subprocess

# Set up Flask app
app = Flask(__name__)

# Set your ngrok auth token (replace with your actual ngrok authtoken)
from pyngrok import ngrok
ngrok.set_auth_token("2qAPib2RMjZdfSm8IzVIqyAZgUI_6xbwzrnHEboxhuhCePdpj")  # Replace with your authtoken

# Create ngrok tunnel
public_url = ngrok.connect(5000)
print(f" * ngrok tunnel \"{public_url}\" -> \"http://127.0.0.1:5000\"")

# Define the endpoint for text-to-speech generation
@app.route('/generate_wav', methods=['POST'])
def generate_wav():
    data = request.get_json()

    # Get the required fields from the request data
    sample_text = data.get("sample_text")
    language = data.get("language")
    gender = data.get("gender")
    alpha = data.get("alpha", 1)
    output_file = data.get("output_file", "/content/Fastspeech2_HS/output.wav")

    # Validate input data
    if not sample_text or not language or not gender:
        return jsonify({"error": "Missing required fields."}), 400Unfortunately, to help prevent spam, we require that you log in to GNOME Shell Extensions in order to post a comment or report an error. You understand, right?



    # Run the inference script to generate speech
    inference_command = [
        "python", "/content/Fastspeech2_HS/inference.py",
        "--sample_text", sample_text,
        "--language", language,
        "--gender", gender,
        "--alpha", str(alpha),
        "--output_file", output_file
    ]

    # Run the inference script and wait for completion
    try:
        subprocess.run(inference_command, check=True)
        return send_file(output_file, as_attachment=True)  # Send the wav file back
    except subprocess.CalledProcessError as e:
        return jsonify({"error": str(e)}), 500

# Run the Flask app
if __name__ == '__main__':
    app.run(port=5000)

!pip install flask-cors

import os
import json
from flask import Flask, request, jsonify, send_file
from pyngrok import ngrok
from flask_cors import CORS
import subprocess

# Set up Flask app
app = Flask(__name__)
CORS(app)
# Set your ngrok auth token (replace with your actual ngrok authtoken)
ngrok.set_auth_token("2qAPib2RMjZdfSm8IzVIqyAZgUI_6xbwzrnHEboxhuhCePdpj")  # Replace with your authtoken

# Create ngrok tunnel
public_url = ngrok.connect(5000)
print(f" * ngrok tunnel \"{public_url}\" -> \"http://127.0.0.1:5000\"")

# Define the endpoint for text-to-speech generation
@app.route('/generate_wav', methods=['POST'])
def generate_wav():
    data = request.get_json()

    # Get the required fields from the request data
    sample_text = data.get("sample_text")
    language = data.get("language")
    gender = data.get("gender")
    alpha = data.get("alpha", 1)
    output_file = data.get("output_file", "output.wav")

    # Validate input data
    if not sample_text or not language or not gender:
        return jsonify({"error": "Missing required fields."}), 400

    # Construct the inference command
    inference_command = f"!python3 /content/Fastspeech2_HS/inference.py --sample_text \"{sample_text}\" --language {language} --gender {gender} --alpha {alpha} --output_file {output_file}"

    # Run the inference script using os.system (Colab-compatible)
    try:
      result = subprocess.run(
    ["python3", "inference.py",  # relative path now
     "--sample_text", sample_text,
     "--language", language,
     "--gender", gender,
     "--alpha", str(alpha),
     "--output_file", output_file],
    cwd="/content/Fastspeech2_HS",  # set working directory
    check=True,
    text=True,
    capture_output=True
)
      response = send_file(output_file, as_attachment=True)
      response.headers.add("Access-Control-Allow-Origin", "*")
      return response
      #return send_file(output_file, as_attachment=True)
      print(result.stdout)
      print(result.stderr)
    except subprocess.CalledProcessError as e:
      print("Error:", e.stderr)

# Run the Flask app
if __name__ == '__main__':
    app.run(port=5000)



!python3 /content/Fastspeech2_HS/inference.py --sample_text "ಹಲೋ, ನಾನು ಮತ್ತು ನನಗೆ ಸಹಾಯ ಬೇಕು." --language kannada --gender male --alpha 1 --output_file male_kannada_output.wav

