# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqfCNrAPSLAEPfGa5NiaHlCMmcZNEbZV
"""

!pip install datasets
!pip install transformers

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, TrainingArguments, Trainer
from datasets import load_dataset, Dataset

# Load and process dataset
import json

with open("/content/train_fixed.json", "r") as file: # you can find the train_fixed.json in the flask-server/training_data folder.
    data = json.load(file)

# Convert to Hugging Face Dataset
dataset = Dataset.from_dict({
    "input": [entry["input"] for entry in data],
    "output": [entry["output"]["text"] for entry in data],
})

# Split dataset into train and test sets
train_test_split = dataset.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

# Model and tokenizer
model_name = "t5-small"  # You can use any T5-based model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Tokenization
def preprocess_function(examples):
    inputs = examples["input"]
    print(examples["output"])
    outputs = examples["output"]  # Correct way to access text

    model_inputs = tokenizer(inputs, max_length=128, truncation=True, padding="max_length")
    print("Tokenized inputs:", model_inputs)  # Check tokenized inputs
    labels = tokenizer(outputs, max_length=128, truncation=True, padding="max_length")
    print("Tokenized labels:", labels)  # Check tokenized labels

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Training setup
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=30,
    weight_decay=0.01,
    save_total_limit=1,
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=10,
    push_to_hub=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
)

# Train the model
trainer.train()

# Save the model
trainer.save_model("finetuned_t5")

!pip install flask pyngrok
!pip install flask-cors

from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from pyngrok import ngrok
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import wave
from google import genai
import google.generativeai as gen
from google.genai import types

# ---------------------- CONFIGURATION ----------------------
GENAI_API_KEY = "Please add your gemini api key"
NGROK_AUTH_TOKEN = "Please add your ngrok auth token"
MODEL_PATH = "/content/finetuned_t5"
TTS_MODEL = "gemini-2.5-flash-preview-tts"
SUPPORTED_LANGUAGES = ["English", "Hindi", "Kannada", "Tamil", "Telugu"]

# ---------------------- INITIALIZATION ----------------------
app = Flask(__name__)
CORS(app)

client = genai.Client(api_key=GENAI_API_KEY)
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_PATH)

ngrok.set_auth_token(NGROK_AUTH_TOKEN)
public_url = ngrok.connect(5000)
print(f" * ngrok tunnel: {public_url}")

gemini_chat = gen.GenerativeModel("gemini-2.0-flash").start_chat(history=[])

# ---------------------- HELPERS ----------------------
def save_wave_file(filename, pcm_data, channels=1, rate=24000, sample_width=2):
    with wave.open(filename, "wb") as wf:
        wf.setnchannels(channels)
        wf.setsampwidth(sample_width)
        wf.setframerate(rate)
        wf.writeframes(pcm_data)

def generate_sentence_from_words(words):
    inputs = tokenizer(words, return_tensors="pt", max_length=128, truncation=True, padding=True)
    outputs = model.generate(
        inputs["input_ids"],
        max_length=128,
        num_beams=5,
        temperature=1.0,
        top_k=50,
        top_p=0.95,
        do_sample=True,
        early_stopping=True
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def grammar_correct(text):
    resp = gemini_chat.send_message(
        f"Make this grammatically correct: {text}. Return only the corrected sentence or the same sentence if it is already correct."
    )
    for r in resp:
        return r.text
    return text

def translate_sentence(text, language):
    if language not in SUPPORTED_LANGUAGES:
        language = "English"
    if language == "English":
        return text
    resp = gemini_chat.send_message(
        f"Translate this to {language}: {text}. Only give translated text."
    )
    for r in resp:
        return r.text
    return text

def generate_audio_file(text, voice="Kore", output_file="output.wav"):
    response = client.models.generate_content(
        model=TTS_MODEL,
        contents=text,
        config=types.GenerateContentConfig(
            response_modalities=["AUDIO"],
            speech_config=types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=voice
                    )
                )
            ),
        )
    )
    audio_data = response.candidates[0].content.parts[0].inline_data.data
    save_wave_file(output_file, audio_data)
    return output_file

# ---------------------- ROUTES ----------------------
@app.route("/generate_sentence", methods=["POST"])
def api_generate_sentence():
    data = request.get_json()
    words = data.get("words")

    if not words:
        return jsonify({"error": "Missing 'words'"}), 400

    try:
        raw_sentence = generate_sentence_from_words(words)
        sentence = grammar_correct(raw_sentence)
        return jsonify({"sentence": sentence})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/translate_sentence", methods=["POST"])
def api_translate_sentence():
    data = request.get_json()
    sentence = data.get("sentence")
    language = data.get("language")

    if not sentence or not language:
        return jsonify({"error": "Missing 'sentence' or 'language'"}), 400

    try:
        translated = translate_sentence(sentence, language)
        return jsonify({"translated_sentence": translated})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/generate_audio", methods=["POST"])
def api_generate_audio():
    data = request.get_json()
    text = data.get("text")
    voice = data.get("voice", "Kore")
    output_file = data.get("output_file", "out.wav")

    if not text:
        return jsonify({"error": "Missing 'text' field in request"}), 400

    try:
        audio_file = generate_audio_file(text, voice, output_file)
        response = send_file(audio_file, as_attachment=True)
        response.headers.add("Access-Control-Allow-Origin", "*")
        return response
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ---------------------- MAIN ----------------------
if __name__ == "__main__":
    app.run(port=5000)