# -*- coding: utf-8 -*-
"""polished.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1jEqXxI6a2LyALFBYedN5XvpLhmtVII
"""

!pip install datasets
!pip install transformers

import json

# Path to input and output files
input_file = "/content/train.json"  # Your current file
output_file = "/content/train_fixed.json"  # Output file expected by the model

# Read the input file
with open(input_file, "r") as file:
    content = file.read()

# Fix the missing array structure and parse JSON objects
# Ensure objects are separated properly
objects = content.strip().split("}\n{")
objects = [f"{{{obj.strip()}}}" for obj in objects]  # Wrap each object correctly

# Parse each object and fix output structure
data = []
for obj in objects:
    try:
        json_obj = json.loads(obj)
        json_obj["output"]["text"] = json_obj["output"]["text"][0]  # Convert to single string
        data.append(json_obj)
    except json.JSONDecodeError as e:
        print(f"Error parsing object: {obj}")
        print(f"Error: {e}")

# Save the corrected JSON as an array
with open(output_file, "w") as file:
    json.dump(data, file, indent=4)

print(f"Corrected JSON saved to {output_file}")

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, TrainingArguments, Trainer
from datasets import load_dataset, Dataset

# Load and process dataset
import json

with open("/content/train_fixed.json", "r") as file:
    data = json.load(file)

# Convert to Hugging Face Dataset
dataset = Dataset.from_dict({
    "input": [entry["input"] for entry in data],
    "output": [entry["output"]["text"] for entry in data],
})

# Split dataset into train and test sets
train_test_split = dataset.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
test_dataset = train_test_split['test']

# Model and tokenizer
model_name = "t5-small"  # You can use any T5-based model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Tokenization
def preprocess_function(examples):
    inputs = examples["input"]
    print(examples["output"])
    outputs = examples["output"]  # Correct way to access text

    model_inputs = tokenizer(inputs, max_length=128, truncation=True, padding="max_length")
    print("Tokenized inputs:", model_inputs)  # Check tokenized inputs
    labels = tokenizer(outputs, max_length=128, truncation=True, padding="max_length")
    print("Tokenized labels:", labels)  # Check tokenized labels

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Training setup
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=30,
    weight_decay=0.01,
    save_total_limit=1,
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=10,
    push_to_hub=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    tokenizer=tokenizer,
)

# Train the model
trainer.train()

# Save the model
trainer.save_model("finetuned_t5")

!pip install flask-ngrok
!wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
!tar -xvzf ngrok-v3-stable-linux-amd64.tgz
!pip install flask-cors
!pip install git+https://github.com/huggingface/parler-tts.git

!./ngrok config add-authtoken 2lPXjpA7kCFuM5gcV3VjaF7uVTO_7bXNgYGwZVTw7EePLFWBD

import cv2
import numpy as np
import google.generativeai as genai

from flask import Flask, request, jsonify
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import subprocess
import time
from flask_cors import CORS

app = Flask(__name__)

CORS(app)

genai.configure(api_key="AIzaSyAJO3IpCicaMJ-i88AUmIrBEyJnQLJlO0g")
model = genai.GenerativeModel("gemini-2.0-flash")
chat = model.start_chat(history=[])

def get_gemini_response(question):
  response = chat.send_message(question)
  return response

# Load the fine-tuned model and tokenizer
model_name = "/content/finetuned_t5"  # Path to your fine-tuned model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Define a function to generate predictions
def generate_response(input_text):
    # Tokenize the input text
    inputs = tokenizer(input_text, return_tensors="pt", max_length=128, truncation=True, padding=True)

    # Generate predictions using the model
    outputs = model.generate(
        inputs["input_ids"],
        max_length=128,  # Increase max_length for longer sequences
        num_beams=5,  # Beam search to improve generation quality
        temperature=1.0,  # Temperature to control randomness (1.0 is standard)
        top_k=50,  # Controls the number of top-k candidate tokens
        top_p=0.95,  # Nucleus sampling to consider a smaller subset of probabilities
        do_sample=True,  # Enable sampling for more varied responses
        early_stopping=True
    )

    # Decode the model's output
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

def gemini_helper(text):
    x = (get_gemini_response("Can you make the following text grammatically accurate "+ text +"." + "Give only the corrected text as response."))
    for i in x:
      return i.text
    return text

def translate(text,language):
    if language not in ["English", "Kannada", "Telugu", "Tamil", "Hindi"]:
      language = "English"
    if language == "English":
      return text
    response = (get_gemini_response("Can you translate the following "+text+" from english to " + language))
    for i in response:
      return i.text
    return text

def translateall(text):
    languages = ["English", "Kannada", "Telugu", "Tamil", "Hindi"]
    processed = {}
    for language in languages:
      response = (get_gemini_response("Can you translate the following "+text+" from english to " + language + "." + "Give only the translated text as response."))
      for i in response:
        processed[language] = i.text
    return processed

@app.route('/generate', methods=['POST'])
def generate():
    try:
        # Parse the JSON payload from the request
        data = request.get_json()
        if not data or 'text' not in data:
            return jsonify({"error": "Missing 'text' in request body"}), 400

        # Call your generate_response function
        response_text = generate_response(data['text'])
        corrected_text = gemini_helper(response_text)
        translated_text = translate(corrected_text, data['language'])
        # Return the response as JSON
        return jsonify({"response": corrected_text,
                        "translated": translated_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/generateall', methods=['POST'])
def generateall():

    try:
        # Parse the JSON payload from the request
        data = request.get_json()
        if not data or 'text' not in data:
            return jsonify({"error": "Missing 'text' in request body"}), 400
        print(data)
        # Call your generate_response function
        response_text = generate_response(data['text'])
        corrected_text = gemini_helper(response_text)
        translated_text = translateall(corrected_text)
        # Return the response as JSON
        return jsonify({"response": corrected_text,
                        "translated": translated_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# Start ngrok
def start_ngrok():
    print("Starting ngrok...")
    ngrok_process = subprocess.Popen(["./ngrok", "http", "5000"])
    time.sleep(3)  # Give ngrok time to start
    ngrok_url = subprocess.check_output(["curl", "-s", "http://localhost:4040/api/tunnels"]).decode("utf-8")
    print("ngrok URL:", ngrok_url)
    return ngrok_process

if __name__ == '__main__':
    # Start ngrok manually
    ngrok_process = start_ngrok()
    try:
        app.run(port=5000)
    finally:
        # Terminate the ngrok process when the server shuts down0
        ngrok_process.terminate()

from flask import Flask, request, jsonify
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import subprocess
import time
from flask_cors import CORS

app = Flask(__name__)

CORS(app)

genai.configure(api_key="AIzaSyAxYW4h33VbLvS4iwjkQQMQlTzSfRk7UPw")
model = genai.GenerativeModel("gemini-2.0-flash")
chat = model.start_chat(history=[])

def get_gemini_response(question):
  response = chat.send_message(question)
  return response

# Load the fine-tuned model and tokenizer
model_name = "/content/finetuned_t5"  # Path to your fine-tuned model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Define a function to generate predictions
def generate_response(input_text):
    # Tokenize the input text
    inputs = tokenizer(input_text, return_tensors="pt", max_length=128, truncation=True, padding=True)

    # Generate predictions using the model
    outputs = model.generate(
        inputs["input_ids"],
        max_length=128,  # Increase max_length for longer sequences
        num_beams=5,  # Beam search to improve generation quality
        temperature=1.0,  # Temperature to control randomness (1.0 is standard)
        top_k=50,  # Controls the number of top-k candidate tokens
        top_p=0.95,  # Nucleus sampling to consider a smaller subset of probabilities
        do_sample=True,  # Enable sampling for more varied responses
        early_stopping=True
    )

    # Decode the model's output
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

def gemini_helper(text):
    x = (get_gemini_response("Can you make the following text grammatically accurate "+ text +"." + "Give only the corrected text as response."))
    for i in x:
      return i.text
    return text

def translate(text,language):
    if language not in ["English", "Kannada", "Telugu", "Tamil", "Hindi"]:
      language = "English"
    if language == "English":
      return text
    response = (get_gemini_response("Can you translate the following "+text+" from english to " + language))
    for i in response:
      return i.text
    return text

def translateall(text):
    languages = ["English", "Kannada", "Telugu", "Tamil", "Hindi"]
    processed = {}
    for language in languages:
      response = (get_gemini_response("Can you translate the following "+text+" from english to " + language + "." + "Give only the translated text as response."))
      for i in response:
        processed[language] = i.text
    return processed

@app.route('/generate', methods=['POST'])
def generate():
    try:
        # Parse the JSON payload from the request
        data = request.get_json()
        if not data or 'text' not in data:
            return jsonify({"error": "Missing 'text' in request body"}), 400

        # Call your generate_response function
        response_text = generate_response(data['text'])
        corrected_text = gemini_helper(response_text)
        translated_text = translate(corrected_text, data['language'])
        # Return the response as JSON
        return jsonify({"response": corrected_text,
                        "translated": translated_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/generateall', methods=['POST'])
def generateall():
    try:
        # Parse the JSON payload from the request
        data = request.get_json()
        if not data or 'text' not in data:
            return jsonify({"error": "Missing 'text' in request body"}), 400

        # Call your generate_response function
        response_text = generate_response(data['text'])
        corrected_text = gemini_helper(response_text)
        translated_text = translateall(corrected_text)
        # Return the response as JSON
        return jsonify({"response": corrected_text,
                        "translated": translated_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# Start ngrok
def start_ngrok():
    print("Starting ngrok...")
    ngrok_process = subprocess.Popen(["./ngrok", "http", "5000"])
    time.sleep(3)  # Give ngrok time to start
    ngrok_url = subprocess.check_output(["curl", "-s", "http://localhost:4040/api/tunnels"]).decode("utf-8")
    print("ngrok URL:", ngrok_url)
    return ngrok_process

if __name__ == '__main__':
    # Start ngrok manually
    ngrok_process = start_ngrok()
    try:
        app.run(port=5000)
    finally:
        # Terminate the ngrok process when the server shuts down0
        ngrok_process.terminate()

